# Generated by Django 4.2.2 on 2025-01-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdProjects',
            fields=[
                ('adprojid', models.AutoField(primary_key=True, serialize=False)),
                ('campaignTitle', models.TextField(default='*')),
                ('status', models.TextField(default='*')),
                ('metadata', models.TextField(default='*')),
                ('rawTest', models.TextField(default='*')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
