# Generated by Django 5.1.5 on 2025-01-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adprojects',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
