# Generated by Django 5.1.5 on 2025-01-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_adprojects_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adprojects',
            name='gptinsights',
            field=models.TextField(default='*'),
        ),
    ]
